services:
  nginx:
    image: nginx:1.27.0-alpine
    restart: unless-stopped
    ports:
      - ${NGINX_PORT_OUT}:${NGINX_PORT}
      - ${NGINX_SSL_OUT}:${NGINX_SSL}
    volumes:
      - ./etc/nginx/conf.d:/etc/nginx/conf.d:ro
      # Default directory.
      #- :/usr/share/nginx/html
    #env_file:
    #  - ./.env

  react-app:
    image: ${PROJECT_NAME}-dev
    build:
      dockerfile: Dockerfile.dev
    #container_name: ${PROJECT_NAME}-dev_c
    restart: unless-stopped
    #ports:
    #  - ${REACT_PORT_OUT}:${REACT_PORT}
    volumes:
      - ./src:/app
      - node_modules:/app/node_modules
    environment:
      - NODE_ENV=development
      - REACT_APP_NAME=${PROJECT_NAME}
      - REACT_PORT=${REACT_PORT}
    #env_file:
    #  - ./.env
    depends_on:
      - nginx

volumes:
  node_modules: