services:
  nginx:
    image: nginx:1.27.0-alpine
    restart: unless-stopped
    ports:
      - ${NGINX_PORT_OUT}:${NGINX_PORT}
      - ${NGINX_SSL_OUT}:${NGINX_SSL}
    volumes:
      - ./etc/nginx/conf.d:/etc/nginx/conf.d:ro

  react-app:
    #image: ${PROJECT_NAME}-dev
    build:
      dockerfile: Dockerfile.dev
      args:
        # Use user id & group id in .env
        USER_ID: ${USER_ID:-0}
        GROUP_ID: ${GROUP_ID:-0}
    #container_name: ${PROJECT_NAME}-dev_c
    #user: ${USER_ID}:${GROUP_ID}
    restart: unless-stopped
    #ports:
    #  - ${REACT_PORT_OUT}:${REACT_PORT}
    volumes:
      - ./src:/app:ro
      - node_modules:/app/node_modules
    environment:
      - NODE_ENV=development
      - REACT_PORT=${REACT_PORT}
      # Set the logins and groups identical to host environment
      - /etc/group:/etc/group:ro
      - /etc/passwd:/etc/passwd:ro
      - /etc/shadow:/etc/shadow:ro
    #env_file:
    #  - ./.env
    depends_on:
      - nginx

volumes:
  node_modules: