services:
  react-app:
    #image: ${PROJECT_NAME}-prod
    build:
      dockerfile: Dockerfile.prod
    #container_name: ${PROJECT_NAME}-prod_c
    ports:
      - ${REACT_PORT_OUT}:${REACT_PORT}
    environment:
      - NODE_ENV=production
      - REACT_PORT=${REACT_PORT}
    #env_file:
    #  - ./.env