services:
  react-app:
    image: react-app:nginx
    container_name: react_app_c
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - ${REACT_PORT_OUT}:${REACT_PORT}
    environment:
      - REACT_PORT=${REACT_PORT}
    #env_file:
    #  - ./.env