services:
  nginx:
    image: nginx:1.27.0-alpine
    container_name: ${NGINX_HOST}_c
    restart: unless-stopped
    ports:
      - 8080:80
    volumes:
      - ./etc/nginx/conf.d:/etc/nginx/conf.d:ro

  react-app:
    build:
      context: .
      dockerfile: Dockerfile.dev
      args:
        # Use user id & group id in .env
        USER_ID: ${USER_ID:-0}
        GROUP_ID: ${GROUP_ID:-0}
    #user: ${USER_ID}:${GROUP_ID}
    restart: unless-stopped
    #ports:
    #  - ${REACT_PORT_OUT}:${REACT_PORT}
    volumes:
      - ./src:/app:ro
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - REACT_PORT=${REACT_PORT}
      # Set the logins and groups identical to host environment
      - /etc/group:/etc/group:ro
      - /etc/passwd:/etc/passwd:ro
      - /etc/shadow:/etc/shadow:ro
    #env_file:
    #  - ./.env
    depends_on:
      - nginx