# Base image.
FROM node:22.6.0-alpine

# Set evironment variables.
ENV LANG=C.UTF-8

# Set up working directory.
WORKDIR /app

# Copy package.json file to working directory.
COPY /src/package.json .

# Install packages.
RUN npm install

# Copy directory.
COPY /src .

# Document exposed port.
EXPOSE ${REACT_PORT}

# Start app.
CMD ["npm", "start"]